#+TITLE: CMP223
#+AUTHOR: Anderson M. Maliszewski
#+STARTUP: overview indent
#+TAGS: noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)

This repository is for the *CMP223 - Computer System Performance*
*Analysis (2019/2)* final work, and has the entire project used to
perform it. Below are the files and folders, along with the analysis
environment. Mode details on how to reproduce the experiments are in
[[LabBook.org]].

* Folders and Files Description
- [[LOGS]] - This folder has the benchmark execution logs in the CSV files
  (~apps_exec~, ~apps_charac~, ~imb_exec~, ~imb_charac~, and ~intel~), four
  machine files ([[LOGS/nodes_full][nodes_full]], [[LOGS/nodes_power_of_2][nodes_power_of_2]], [[LOGS/nodes_square_root][nodes_square_root]] and
  [[LOGS/nodes_intel][nodes_intel]] used by the MPI execution line, a file containing the
  [[LOGS/env_info.org][environment information]] used in the experiments, and a folder called
  [[LOGS/BACKUP][BACKUP]] that includes the application logs without any modification.
- [[PLOTS]] - Here are the graphs of the analysis made with the execution
  time of the applications, as well as its characterization genereted
  with R statistical language.
- [[R]] - This folder has the Design of Experiments output (made in the
  [[LabBook.org][LabBook.org]] → Experiment Project → Design of Experiments), called
  [[R/experimental_project][experimental_project]], which is responsible for random
  applications/network interface combinations using 30 execution
  replications for normal execution and 1 replication for
  characterization execution.
- [[SH]] - Here are five bash scripts ([[SH/benchmark][benchmark]], [[SH/central][central]],
  [[SH/software_install][software_install]], [[SH/sys_info_collect][sys_info_collect]]) that are used to perform the
  experiments and collect system information.
- [[BENCHMARKS]] - This folder has all the five benchmarks (Alya,
  ImbBench, Intel MPI Benchmarks, Nas Parallel Benchmarks, and
  Ondes3d) subdivided into execution and characterization
  folders. This was made because the benchamarks execution used the
  mpicc and/or mpifort compiler, and the benchmarks characterization
  used the Score-P and the mpicc and/or mpifort compiler to generate
  the binaries that are traced during its execution.
- [[SOFTWARE]] - Here are the three softwares ([[https://www.vi-hps.org/projects/score-p/][Score-P]], [[https://github.com/schnorr/akypuera][Akypuera]], and
  [[https://github.com/schnorr/pajeng][PajeNG]]) used in the tracing process.
- [[LabBook.org]] - In this file is described the objective of this work,
  as well as the step-by-step execution of the entire project.

* Analysis Environment 
Some specific softwares are necessary to reproduce this evaluation
accurately. They are:
- Emacs and Org - They are used as a project management tool to track,
  record all the information, and generate the graphics using R code
  blocks. A complete tutorial on how to install and configure the
  mentioned softwares are available [[https://app-learninglab.inria.fr/gitlab/learning-lab/mooc-rr-ressources/blob/master/module2/ressources/emacs_orgmode.org][here]]. If you do not want to use
  this softwares, you can copy the blocks of code and use R or RStudio
  to generate the graphics.
 

